import glob
import os
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.v2 import Compose, Resize, ToImage, ToDtype

class CaltechJotDataset(Dataset):
    """Loads images directly from nested category subfolders generated by Beam."""
    def __init__(self, root_dir, label_to_idx, transform=None):
        self.root_dir = root_dir
        self.label_to_idx = label_to_idx
        
        # 1. Recursively find all JPG images inside class subdirectories
        # Example match: /path/train/airplane/caltech-train-00000.jpg
        self.image_paths = glob.glob(os.path.join(root_dir, "*", "*.jpg"))
        
        # Default transforms to convert the PIL images to standardized PyTorch tensors
        self.transform = transform if transform else Compose([
            Resize((224, 224)),
            ToImage(),
            ToDtype(torch.float32, scale=True) # Automatically scales pixels to [0.0, 1.0]
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        
        try:
            # 2. Extract label string from the parent directory name
            # /path/train/airplane/caltech-train-00000.jpg -> parent is "airplane"
            label_name = os.path.basename(os.path.dirname(image_path))
            label_idx = self.label_to_idx[label_name]
            
            # 3. Open image using PIL safely
            with Image.open(image_path) as img:
                img = img.convert('RGB')
                if self.transform:
                    img = self.transform(img)
                    
            return img, label_idx
            
        except Exception as e:
            print(f"Error loading image {image_path}: {e}")
            # Return an empty tensor placeholder or handle your skip strategy here
            return torch.zeros((3, 224, 224)), -1

# Load label dictionary mapping
label_to_idx = {}
with open("./label_map.txt", "r") as f:
    for line in f:
        label_name, idx = line.strip().split()
        label_to_idx[label_name] = int(idx)

gcs_root = "/home/amol/Downloads/archive/"

# 4. Instantiate map-style dataset pointing to the /train folder root
train_dataset = CaltechJotDataset(
    root_dir=os.path.join(gcs_root, "train"),
    label_to_idx=label_to_idx
)

# 5. Native map-style dataloader supports true random shuffling safely
def get_dataloader(dataset, batch_size, shuffle, num_workers=2):
    return DataLoader(
        dataset, 
        batch_size=batch_size, 
        shuffle=shuffle, 
        num_workers=num_workers,
        pin_memory=True
    )

# Example execution usage
train_loader = get_dataloader(train_dataset, batch_size=32, shuffle=True)