#name of pipeline
name: deploy ML training

on:
  push:
    branches:
      - main


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prd
    env:
      SA_KEY: ${{secrets.SA_KEY}}
      IMAGE_URI: "${{vars.IMAGE_URI}}/caltech-mobilenetv2:${{github.sha}}"
      

      
    steps:
      - name: download code
        uses: actions/checkout@v4
      
      - name: gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: build
        run:  sudo docker build -t $IMAGE_URI .

      - name: authenticate using SA
        uses: google-github-actions/auth@v2
        with:
          credentials_json: $SA_KEY 
      - name: configure docker auth mechanism
        run: gcloud auth configure-docker ${{vars.AUTH_URL}}

      - name: push to artifact registry
        run:  sudo docker push -t $IMAGE_URI
