name: deploy ML training

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prd
    env:
      DATA_IMAGE_URI: "${{vars.IMAGE_URI}}/data_preprocessing:${{github.sha}}"
      TRAINING_IMAGE_URI: "${{vars.IMAGE_URI}}/model_training:${{github.sha}}"
    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: authenticate using SA
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.SA_KEY}}
      
      - name: gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: configure docker auth mechanism
        run: gcloud auth configure-docker ${{vars.AUTH_URL}}

     # Step 6: Trigger Airflow DAG
      - name: Trigger Airflow DAG
        run: gcloud compute ssh train-instance \
            --zone us-central1-a \
            --command "airflow dags trigger image_classification_pipeline"